### PR TITLE
[hotfix] Rebrand data Artisans to Ververica

### PR DESCRIPTION
**Pull request by sjwiesman**
Change dA training website to ververica. 

* Slide share is still dataArtisans
* The zh page already points to ververica

### CODE REVIEW

**Comment by sjwiesman** [comment]
cc @fhueske

**Comment by sjwiesman** [comment]
cc @fhueske

**Comment by bowenli86** [comment]
The 'ecosystem' pages still use `dataArtisans`. Can you change them too?

```
$ ag dataartisan
...

ecosystem.md
56:[Cascading on Flink](https://github.com/dataArtisans/cascading-flink) is built by [dataArtisans](http://data-artisans.com/) and [Driven, Inc](http://www.driven.io/).

ecosystem.zh.md
48:[Cascading on Flink](https://github.com/dataArtisans/cascading-flink) 项目是由 [dataArtisans](http://data-artisans.com/) 和 [Driven, Inc](http://www.driven.io/) 建立。请参阅 Fabian Hueske 在 [Flink Forward 会议上的演讲](http://www.slideshare.net/FlinkForward/fabian-hueske-training-cascading-on-flink)以获取更多细节。
```

**Comment by sjwiesman** [comment]
Thanks for taking a look @bowenli86 

The ecosystem page refers to cascading on flink which is still hosted in the data artisans github repo. It also hasn't been worked on in over three years so I'd prefer to leave that as is and potentially remove it from the website entirely.

**Comment by fhueske** [comment]
Thanks for the PR @sjwiesman!

The `ecosystem.md` is currently not linked to the website and reworked in PR #187. The Cascading on Flink entry is removed btw.

I'll merge it.

**Pull request closed without merging**
