### PR TITLE
[FLINK-17926] Fix the build problem of docker image

### PR DESCRIPTION
**Pull request by klion26**
Currently, we use Ubuntu:18.10 to build the docker image, but Ubuntu:18.10 has reached the end of life.
In this commit we change to the closest LTS version 18.04

### CODE REVIEW

**Comment by klion26** [comment]
cc @rmetzger

**Review by rmetzger — CHANGES_REQUESTED** [review]
It seems that building the docs doesn't work anymore?

```
$ ./build.sh  -p
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```

**Comment by klion26** [comment]
@rmetzger thanks for the review, before filing pr just verified `./build.sh -p` after executing `./docker/run.sh`, but did not verified call `./build.sh -p` directly, will investigate it.

**Comment by klion26** [comment]
@rmetzger I traced this problem, found that it's some issue about local environment. I reproduced this problem on my personal laptop(both failed on this branch and `asf-site` branch), I fixed the problem by following this [gist](https://gist.github.com/fernandoaleman/868b64cd60ab2d51ab24e7bf384da1ca) and upgrading my ruby version using `brew install ruby`(after the installation, ruby version is `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]`)

I can't fix this problem on ruby-2.6(tried all the solutions I can find, neither worked on my laptop because of can't install `therubyracer` successfully :disappointed:)

when executing `./build.sh -p` with ruby 2.7 jekyll, will output some warning log on screen `/Users/congxianqiu/klion26/flink-web/.rubydeps/ruby/2.7.0/gems/jekyll-3.0.5/lib/jekyll/url.rb:110: warning: URI.escape is obsolete`, I've filed an question on [jekyllrb](https://talk.jekyllrb.com/t/too-many-warning-messages-when-using-ruby-2-7-1p83-with-jekyll-3-0-5/4480)

**Comment by rmetzger** [comment]
Thanks for investigating. How about using a Docker image that ships with ruby 2.7.1 ? (what about newer Ubuntu versions?)
We don't have to stick to an ubuntu-based docker image.

**Comment by sjwiesman** [comment]
How about using the Dockerfile from the docs in the main repo. It contains everything and we already know it works with our Jekyll setup.  

https://github.com/apache/flink/blob/master/docs/docker/Dockerfile

**Comment by klion26** [comment]
@sjwiesman thanks for the replay, previously I prefer using Ubuntu image because that Ubuntu support LTS version, and Fedora doesn't. I'm fine to use Fedora image if we want to use it here.
cc @rmetzger

**Comment by rmetzger** [comment]
I'm fine with any distribution

**Comment by rmetzger** [comment]
@klion26 I tested it with my other mac book as well, and the same error occurs. Deleting .bundle and .rubydeps in the docs directory (and the home directory) did not resolve the problem.

Did it work for you @sjwiesman ?

**Comment by klion26** [comment]
@rmetzger hmm. seems there is some problem after applying this patch(not sure whether it was there before applying this patch), but I can't reproduce it using this patch now.

When trying to use the base image from main repo as @sjwiesman suggested, encounter some errors, I'm trying to fix such error on my side(using the dockerfile from main repo).

```
Configuration file: /Users/congxianqiu/klion26/flink-web/_config.yml
  Dependency Error: Yikes! It looks like you don't have /Users/congxianqiu/klion26/flink-web/_plugins/highlightCode.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the /Users/congxianqiu/klion26/flink-web/_plugins/highlightCode.rb gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- pygments' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
bundler: failed to load command: jekyll (/Users/congxianqiu/klion26/flink-web/.rubydeps/ruby/2.5.0/bin/jekyll)
J
```

PS: the Dockerfile in the main repo can run on my laptop successfully.

**Comment by rmetzger** [comment]
I just realized that I usually don't use the `docker/run.sh` approach for building the docs. I use what is [documented on the website](https://flink.apache.org/contributing/improve-website.html#update-or-extend-the-documentation):
```
docker run --rm --volume="$PWD:/srv/flink-web" --expose=4000 -p 4000:4000 -it ruby:2.5 bash -c 'cd /srv/flink-web && ./build.sh -p'
```

Maybe the files created by the `ruby:2.5` docker image are not compatible with the files from `docker/run.sh`

**Comment by klion26** [comment]
Ahh. maybe there is someting not compatible with `ruby:2.5` docker image, I tried to execute the command `docker run --rm --volume="$PWD:/srv/flink-web" --expose=4000 -p 4000:4000 -it ruby:2.5 bash -c 'cd /srv/flink-web && ./build.sh -p'` on my laptop, it failed with the following message, I'll try to find out the reason here.
```
Configuration file: /srv/flink-web/_config.yml
bundler: failed to load command: jekyll (/srv/flink-web/.rubydeps/ruby/2.5.0/bin/jekyll)
LoadError: libruby-2.5.so.2.5: cannot open shared object file: No such file or directory - /srv/flink-web/.rubydeps/ruby/2.5.0/gems/posix-spawn-0.3.14/lib/posix_spawn_ext.so
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/posix-spawn-0.3.14/lib/posix/spawn.rb:2:in `require'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/posix-spawn-0.3.14/lib/posix/spawn.rb:2:in `<top (required)>'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:2:in `require'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:2:in `<top (required)>'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/pygments.rb-0.6.3/lib/pygments.rb:1:in `require'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/pygments.rb-0.6.3/lib/pygments.rb:1:in `<top (required)>'
  /srv/flink-web/_plugins/highlightCode.rb:22:in `require'
  /srv/flink-web/_plugins/highlightCode.rb:22:in `<top (required)>'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:75:in `require'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:74:in `each'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:73:in `each'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/site.rb:97:in `setup'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/site.rb:49:in `initialize'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/commands/build.rb:30:in `new'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/commands/build.rb:30:in `process'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /srv/flink-web/.rubydeps/ruby/2.5.0/gems/jekyll-3.0.5/bin/jekyll:17:in `<top (required)>'
  /srv/flink-web/.rubydeps/ruby/2.5.0/bin/jekyll:23:in `load'
  /srv/flink-web/.rubydeps/ruby/2.5.0/bin/jekyll:23:in `<top (required)>'
```
@rmetzger can `./docker/run.sh` success on your side?

**Comment by rmetzger** [comment]
`./docker/run.sh` successfully starts the docker container, but inside the container, I can not execute `./build.sh -p`.
Have you tried deleting `.rubydeps` to fix the problem you've mentioned?


What about removing the `./docker` directory and using 
```
docker run --rm --volume="$PWD:/srv/flink-web" --expose=4000 -p 4000:4000 -it ruby:2.5 bash -c 'cd /srv/flink-web && ./build.sh -p'
```
As the only official way to build the Flink website?

**Comment by klion26** [comment]
delete `.rubydeps` works for me, thanks for the fix.

I'm fine to remove the `./docker` directory and using the command as the only official way to build the Flink website. I'll push another commit to remove the `./docker` directory.

`docker run --rm --volume="$PWD:/srv/flink-web" --expose=4000 -p 4000:4000 -it ruby:2.5 bash -c 'cd /srv/flink-web && ./build.sh -p'`

**Comment by rmetzger** [comment]
Thanks! Maybe add the docker command into the readme of the repository, to make it easier to find ?

**Comment by klion26** [comment]
Pushed another commit:
- remove the `./docker` directory
- add the command in `README.md`

**Comment by rmetzger** [comment]
Thanks a lot, merging

**Comment by klion26** [comment]
@rmetzger @sjwiesman  thanks for the review and merging.

**Pull request closed without merging**
