### PR TITLE
Add Didi to PowerBy page

### PR DESCRIPTION
**Pull request by wuchong**
Add DiDi to PowerBy Page.

Here is a preview:

Here is a Chinese-version preview:

image

### CODE REVIEW

**Comment by wuchong** [comment]
Hi @rmetzger  @fhueske , do you need to have a look?

**Comment by rmetzger** [comment]
Thanks for opening this pull request. Do we have approval by Didi to put their logo and this text on the Flink website?

**Comment by rmetzger** [comment]
Great! Thanks for confirming (in https://github.com/apache/flink-web/pull/227)
@fhueske good to go?

**Comment by fhueske** [comment]
Thanks @wuchong!

Will merge this PR as well.

**Pull request closed without merging**
