### PR TITLE
Remove kubernetes operator 0.1.0 from downloads page

### PR DESCRIPTION
**Pull request by gyfora**

### CODE REVIEW

**Review by wangyang0918 — APPROVED** [review]
+1 for removing 0.1 version.

**Comment by wangyang0918** [comment]
image

Do we need to update the stable release version?

**Comment by gyfora** [comment]
> image
> 
> Do we need to update the stable release version?

Yes , let me fix that in this PR a little later

**Comment by gyfora** [comment]
@wangyang0918 I think I fixed the other issue you mentioned :) 

When you are merging this please help me rebuild the website because I can't do it on my M1 mac unfortunately

**Comment by wangyang0918** [comment]
Yes. I will rebuild the website after merging.

**Pull request merged**
