### PR TITLE
Add FLIP to Community Menu and How-To-Contribute

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by aljoscha** [comment]
R: @uce or @rmetzger for review

**Comment by rmetzger** [comment]
+1 to merge

**Comment by uce** [comment]
Same here, +1

**Comment by aljoscha** [comment]
Man, I really think we need a standardized build environment/server for the website. My install generates different pages and pagination is broken and syntax highlighting as well, I think.

**Pull request closed without merging**
