### PR TITLE
Added a hint to the 1.14 RC0 post with a link to the actual release

### PR DESCRIPTION
**Pull request by joemoe**

### CODE REVIEW

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Review by xintongsong — APPROVED** [review]
Thanks @joemoe, LGTM.

The only thing is, a `flink-web` PR should not include changes to the auto-generated files (anything under `content/`). They will be generated will merging the PR. I'll fix it while merging.

**Review by knaufk — CHANGES_REQUESTED** [review]
Could you put the generated html into a separate commit?

**Comment by MartijnVisser** [comment]
This has been resolved since I can see edit at https://flink.apache.org/news/2021/08/31/release-1.14.0-rc0.html

**Pull request closed without merging**
