### PR TITLE
Add tison to community page

### PR DESCRIPTION
**Pull request by TisonKun**

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for opening the PR and congrats again for becoming a committer @TisonKun!

The committer list is alphabetically ordered by last name. Can you move your entry between "Shuyi Chen" and "Xingcan Cui"? We also ask PRs to not include the changed HTML (everything in `./content`). When the PR is merged, we build the website and add the changes in a separate commit (typically with the message "Rebuild website").

Thanks, Fabian

**Comment by TisonKun** [comment]
Thanks for your update @fhueske! I will update. For include changes in HTML I follow this commit a0c3faba64a66bb5c17889f7d893e4b17de6321d. I will revert that change follow your advice.

**Comment by fhueske** [comment]
Thanks for the update! 
+1 to merge. 

@TisonKun, do you want to merge the PR yourself (trying out your commit power) or would you like me to do it?

Thanks, Fabian

**Comment by TisonKun** [comment]
I'd like to try to merge this PR myself. Is it ok that I click "Squash and merge" bottom from GitHub website, or I need to do a push from CLI?

Besides, I'm not sure whether it is also required to commit the following "Rebuild Website" in this pull request. I have rebuilt it locally.

**Comment by fhueske** [comment]
Cool :-)
For the website you need to do merge manually from the CLI because you need to add the "rebuild website" commit. These are the steps that I follow:

* Rebase to current `asf-site`
* Call `./build.sh` to rebuild the website
* Commit changes in `./content` with message "Rebuild website".
* Push both commits to `asf-site` branch in ASF repo

Happy merging,
Fabian

**Comment by TisonKun** [comment]
Thanks for your guidance @fhueske ! I hope I did the right thing :P

**Comment by fhueske** [comment]
Yes, looks good :+1: 😊

Thanks!

**Pull request closed without merging**
