### PR TITLE
[FLINK-2365] Improves How to contribute page

### PR DESCRIPTION
**Pull request by ebautistabar**
- Fixes typos, broken links
- Improves formatting
- Adds reference to the website's GitHub mirror repo

### CODE REVIEW

**Comment by mxm** [comment]
Thanks for updating the IDE instructions, providing information on how to contribute to the website, and fixing many typos!

Looks good to merge from my side.

**Comment by ebautistabar** [comment]
Great! Is there something else I should do?

**Comment by mxm** [comment]
No, looks good. I'll merge your changes later on.

**Comment by mxm** [comment]
Merged as of 1f917e3. Could you please close this pull request? We are missing support for auto-close for this repository :)

**Comment by ebautistabar** [comment]
Sure, I'll close it now. Thanks!

**Pull request closed without merging**
