### PR TITLE
[FLINK-18454] Add a code contribution section about how to look for what to contribute

### PR DESCRIPTION
**Pull request by azagrebin**
The PR adds a code contribution section about how to look for what to contribute to give general advices about browsing open Jira issues and starter tasks.

### CODE REVIEW

**Review by rmetzger — APPROVED** [review]
Thanks a lot for improving the contribution experience!

Remember to keep the chinese translation in sync

**Comment by azagrebin** [comment]
Thanks for the review @rmetzger 
True, my plan was to ask somebody to help with the Chinese translation, once we merge this PR.

**Comment by azagrebin** [comment]
I kindly asked @zhuzhurk to pushed the translation

**Comment by zhuzhurk** [comment]
I just found a problem of flink-web that the anchors of ZH docs are not properly generated. See FLINK-18496.
This blocks us from reference a section with an anchor because the anchor name might change unexpectedly. So it blocks the Chinese translation of this PR.

@rmetzger do you have any idea for it? I'm not quite familiar with the doc generation tool.

**Comment by azagrebin** [comment]
Thanks for the fixup @zhuzhurk and finding the problem with the Chinese translation generation.
I suggest we merge this PR now and open another PR for the Chinese translation once FLINK-18496 is resolved.

**Pull request closed without merging**
