### PR TITLE
Upgrade Kafka connector to 3.3.0

### PR DESCRIPTION
**Pull request by AHeise**

### CODE REVIEW

**Comment by dannycranmer** [comment]
@AHeise we do not usually include the "rebuild website" commit in this PR, this is usually done as a follow up, without PR. Usually the date in the PR is a placeholder and it needs to change later anyway

**Comment by dannycranmer** [comment]
You are missing a change in the release_archive, see here for example https://github.com/apache/flink-web/pull/737/files

**Comment by AHeise** [comment]
> You are missing a change in the release_archive, see here for example https://github.com/apache/flink-web/pull/737/files

Thank you for the pointers. I fixed both issues.

**Comment by leonardBang** [comment]
@AHeise Could you change the PR from DRAFT to READY for review ?

**Comment by leonardBang** [comment]
I changed the status and thus we can start following review

**Review by leonardBang — APPROVED** [review]

**Review by 1996fanrui — APPROVED** [review]
Thanks @AHeise for driving this release!

LGTM.

**Pull request merged**
