### PR TITLE
[blog] Add blog post about broadcast state

### PR DESCRIPTION
**Pull request by fhueske**
A while ago, I wrote and published a blog post on Flink's [broadcast state feature](https://www.ververica.com/blog/a-practical-guide-to-broadcast-state-in-apache-flink).
I think this post would also be a good fit for the Flink blog and I'd like to repost it here.

Please let me know what you think.

Thanks, Fabian

### CODE REVIEW

**Comment by bowenli86** [comment]
+1

**Comment by MarkSfik** [comment]
+1

**Comment by morsapaes** [comment]
+1

**Comment by fhueske** [comment]
Oh, just noticed that this blog post wasn't merged and published yet.
Will do that now.
Cheers, Fabian

**Pull request closed without merging**
