### PR TITLE
Update Gelly documentation link

### PR DESCRIPTION
**Pull request by njzhuyuqi**
Update Gelly documentation link on the flink news web page address http://flink.apache.org/news/2015/08/24/introducing-flink-gelly.html, change to the newest documentation of Gelly.

### CODE REVIEW

**Comment by zhangminglei** [comment]
LGTM, Thanks for @njzhuyuqi contribution.

**Comment by tzulitai** [comment]
Hi @njzhuyuqi, thanks for the PR.
I think we actually need to update the .md file that generates this html, not change the generated html directly. Otherwise every time the site is rebuilt, the link will still be overwritten with the incorrect link.

**Comment by njzhuyuqi** [comment]
hi,  tzulitai , thanks for pointing out this,  I have updated the PR.

**Comment by zhangminglei** [comment]
@njzhuyuqi I believe that you just change the .md file is enough, no need to change html file instead.

**Comment by tzulitai** [comment]
+1, merging!

@zhangminglei it's fine, as long as the markdown file is modified. If the html file isn't modified also in the PR, it would just be a matter of rebuilding the site once the PR is merged.

**Comment by njzhuyuqi** [comment]
yes, i see, thanks zhangminglei and tzulitai.

**Pull request closed without merging**
