### PR TITLE
Flink Kubernetes Operator 1.3.1

### PR DESCRIPTION
**Pull request by gyfora**

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
Looks good, except the jira list which is somehow collapsed.
image

**Comment by gyfora** [comment]
I tired to fix the list @gaborgsomogyi could you please check for me again?

**Comment by gaborgsomogyi** [comment]
After some fix + website regeneration the page looks the following:
Screenshot 2023-01-10 at 15 07 16

**Review by gaborgsomogyi — APPROVED** [review]
LGTM.

**Pull request merged**
