### PR TITLE
Reference flink-connector-parent v1.1.0

### PR DESCRIPTION
**Pull request by echauchot**

### CODE REVIEW

**Review by ruanhang1993 — APPROVED** [review]

**Review by PatrickRen — APPROVED** [review]
LGTM

**Review by 1996fanrui — APPROVED** [review]
Thanks for the release, LGTM.

**Review by leonardBang — APPROVED** [review]
Thanks @echauchot for the work, LGTM

**Review by snuyanzin — APPROVED** [review]

**Review by GOODBOY008 — APPROVED** [review]
Thanks @echauchot  driven this release. LGTM

**Comment by echauchot** [comment]
Thanks everyone for the review. The artifacts were published a day ago (ASF wait delay), merging this PR

**Pull request merged**
