### PR TITLE
[hotfix] Update coding guidelines for JUnit timeouts

### PR DESCRIPTION
**Pull request by dawidwys**

### CODE REVIEW

**Comment by dawidwys** [comment]
cc @AHeise @tillrohrmann @rmetzger @lindong28 @pnowojski

**Review by tillrohrmann — APPROVED** [review]
Thanks for creating this PR @dawidwys. LGTM. +1 for merging.

**Review by pnowojski — APPROVED** [review]

**Review by AHeise — APPROVED** [review]
LGTM.

**Comment by lindong28** [comment]
Thank you @dawidwys for creating the PR. LGTM.

**Pull request merged**
