### PR TITLE
[FLINK-7094] Update outdated doc release 1.2 to latest stable release…

### PR DESCRIPTION
**Pull request by zhangminglei**
… 1.3

### CODE REVIEW

**Comment by zhangminglei** [comment]
@greghogan  Could you please take a review on this PR ?  And only this PR merge first, then we can keep working on FLINK-6995 [ Add a warning to outdated documentation ] which we discussed before.

**Comment by zhangminglei** [comment]
Sup

**Comment by NicoK** [comment]
+1

**Comment by zentol** [comment]
merging

**Pull request closed without merging**
