### PR TITLE
[FLINK-33350] Update website for release 1.18.0

### PR DESCRIPTION
**Pull request by JingGe**
This PR aims to update some config files related to 1.18 release.

This PR is related to #680 - add announcement blog post for Flink 1.18

### CODE REVIEW

**Review by PatrickRen — COMMENTED** [review]
@JingGe Thanks for the PR! LGTM but it'll be better if someone familiar with the new website structure to double-check.

**Review by PatrickRen — APPROVED** [review]
I compared the PR with the commit history we made for 1.17 (3114602). The only difference is that this PR doesn't change the `config.toml` file, but I see this file is changed in the release announcement PR (#680), so I'm gonna approve it.

**Comment by snuyanzin** [comment]
in general lgtm
one question to clarify: is it ok to remove 1.16.x?
I'm asking since AFAIR usually there should be 3 minor releases and the latest after the major is happen

**Comment by PatrickRen** [comment]
@snuyanzin Thanks for the reminder. Yep the [policy](https://flink.apache.org/downloads/#update-policy-for-old-releases) is that we need to release a 1.16.3 after 1.18.0, then drop support for 1.16. 

@JingGe Could you update the PR and keep 1.16 related contents for now? We can remove them after releasing 1.16.3

**Review by PatrickRen — APPROVED** [review]
@JingGe Thanks for the update. LGTM

**Comment by JingGe** [comment]
@snuyanzin good catch! I have addressed it. Please check it again. Thanks!

**Review by snuyanzin — APPROVED** [review]
thanks for addressing

**Pull request merged**
