### PR TITLE
[FLINK-13680] Translate "Common Rules" page into Chinese

### PR DESCRIPTION
**Pull request by ClownfishYang**
**What is the purpose of the change**

Translate "Common Rules" page into Chinese.

**Brief change log**

I modified the "contributing/code-style-and-quality-common.zh.md" file .

**Verifying this change**

I have verified the changes by starting the build script in preview mode.

### CODE REVIEW

**Comment by klion26** [comment]
@ClownfishYang could you please clean the git history by getting rid of the git merge commit(you can use `git rebase` instead), after that I can have a look. thanks.

**Comment by ClownfishYang** [comment]
@klion26 I think it would be easier for me to submit a new request.https://github.com/apache/flink-web/pull/394

**Comment by klion26** [comment]
@ClownfishYang as you've created a new pr, could you please close this one.

**Comment by ClownfishYang** [comment]
OK，My closed it.

**Pull request closed without merging**
