### PR TITLE
[hotfix] Fixing incorrect ID for download tracking

### PR DESCRIPTION
**Pull request by MartijnVisser**
We're tracking download for Flink 1.14.0 Scala 2.12 and source code downloads as Flink 1.13.2 downloads

### CODE REVIEW

**Review by tillrohrmann — APPROVED** [review]
Thanks for creating this fix @MartijnVisser. LGTM. Merging it now.

**Comment by dawidwys** [comment]
Sorry for the mistake :cold_sweat:

**Comment by MartijnVisser** [comment]
No worries :)

**Comment by tillrohrmann** [comment]
Merged via 83ac892dffefda55eb6640fbfca69cb0d5a413f1

**Pull request closed without merging**
