### PR TITLE
Adding AWS Connectors v4.3.0

### PR DESCRIPTION
**Pull request by dannycranmer**

### CODE REVIEW

**Review by jeyhunkarimov — APPROVED** [review]
LGTM, thanks!

**Review by vahmed-hamdy — APPROVED** [review]
LGTM!

**Review by ruanhang1993 — APPROVED** [review]
LGTM.

**Review by z3d1k — APPROVED** [review]
LGTM

**Review by leonardBang — APPROVED** [review]
+1

**Review by GOODBOY008 — APPROVED** [review]
LGTM

**Review by 1996fanrui — APPROVED** [review]
Thanks @dannycranmer for the hard work!

LGTM

**Review by reswqa — APPROVED** [review]
Thanks @dannycranmer, LGTM!

**Pull request merged**
