### PR TITLE
Add yang to community

### PR DESCRIPTION
**Pull request by wangyang0918**
cc @xintongsong Would you like to give me a pass?

### CODE REVIEW

**Review by xintongsong — APPROVED** [review]
flink-web PRs should only include changes to the `.md` files. After the PR being approved, committers should rebuild the website and merge.

Other than that, all look good.

**Comment by wangyang0918** [comment]
Yes. I am using the `build.sh` to generate the second commit.

**Comment by xintongsong** [comment]
I meant the PR should only include your first PR. We usually rebuilt the website while merging the PR, so that the PR only includes changes need to be reviewed, and to make sure always build the website on the latest commit (in case other changes being merged during the review).

Shouldn't be a problem for this PR.

**Comment by wangyang0918** [comment]
I get your point.

**Pull request merged**
