### PR TITLE
[FLINK-5308] download links to previous releases are incomplete

### PR DESCRIPTION
**Pull request by NicoK**
Several Flink releases were missing in the list of all releases on the download page. This adds them and provides a generic link to the archive folder.

### CODE REVIEW

**Comment by NicoK** [comment]
@wints can you have a look?

**Comment by wints** [comment]
Looks good to me, @NicoK. Thanks for the addition.

@uce @rmetzger

**Comment by fhueske** [comment]
Thanks for extending the previous release section @NicoK.
PR is good to merge, IMO.

**Comment by uce** [comment]
+1 to merge. @fhueske are you going to do it?

**Comment by fhueske** [comment]
Yes, will batch it with #43

**Comment by fhueske** [comment]
Mergign

**Pull request closed without merging**
