### PR TITLE
[FLINK-6971] Add a paragraph of Alluxio into Ecosystem page

### PR DESCRIPTION
**Pull request by apc999**
This pull request aims to update the ecosystem page to add a pointer to the guide of using Flink to access Alluxio.

screen shot 2017-06-23 at 1 46 58 pm

### CODE REVIEW

**Comment by wints** [comment]
Thanks @apc999, +1 from my end. 

@rmetzger @uce

**Comment by rmetzger** [comment]
+1 to merge

**Comment by apc999** [comment]
thanks for approving this PR. 
do I need to do anything to merge it? Or we need more +1s?

**Comment by rmetzger** [comment]
No, its just that nobody from the community didn't have the chance to merge it yet.

**Comment by tzulitai** [comment]
LGTM, merging! Thanks for the contribution @apc999.

**Pull request closed without merging**
