### PR TITLE
Added the Gelly Blog Post

### PR DESCRIPTION
**Pull request by andralungu**
Hey @uce,
I heard you are in charge of inspecting the markup around here :). Could you please check mine as well and then merge?

Thinks should be okay... I only had a problem with the Java code snippets in the final section... Seems an extra tab is introduced for all the lines. Did not know how to get rid of that. Can you perhaps help me out a bit? 

Also, if it's not too much to ask for, can this be merged before the meetup Wednesday?

Thanks!! :D

### CODE REVIEW

**Comment by uce** [comment]
Hey Andra, you don't have to write the HTML yourself, but add a file to `_posts` with Markdown (usually).

Check this out: https://cwiki.apache.org/confluence/display/FLINK/Writing+a+Blog+Post

Ping me if you need any help.

**Comment by andralungu** [comment]
Yup, my bad... It's .md now. 
If it's okay, you can merge it!

**Comment by uce** [comment]
OK, this looks good. Did we have consensus to publish the blog post?

**Comment by andralungu** [comment]
Yup... it's been pending for a long while. Check the "Gelly Blog Post" thread on the mailing list :)

**Comment by rmetzger** [comment]
Thank you for writing the blog post @andralungu & @uce for merging it.
I'll tweet about it from @ApacheFlink

**Comment by andralungu** [comment]
And you can also invite people who have questions to the meetup :P

**Pull request closed without merging**
