### PR TITLE
[hotfix][docs]  Fix link tags  typo.

### PR DESCRIPTION
**Pull request by liuzhuang2017**
[hotfix][docs] Fix link tags typo.

### CODE REVIEW

**Comment by liuzhuang2017** [comment]
@wuchong  ,Hi,please help me review this pr when you are free time, thank you.

**Comment by liuzhuang2017** [comment]
@MartijnVisser ,Sorry to bother you, can you help me review this pr? Thank you.

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
@liuzhuang2017 Thanks for the PR, but you're not solving the problem. The HTML files are auto-generated. The issue most likely is caused by an incorrect link in `_includes/navbar.html` which isn't changed in this PR.

**Comment by liuzhuang2017** [comment]
@MartijnVisser ，Thanks for your review, I will try to fix it according to your suggestion.

**Comment by liuzhuang2017** [comment]
@MartijnVisser ，Thanks for your review, I have modified it according to your suggestion.

**Comment by MartijnVisser** [comment]
@liuzhuang2017 The PR currently has conflicts. Also, is there a lot of added value? The link currently already works, it just has a double slash `//` in there. If you still think it has value, please resolve the conflicts, squash your commits and rebase with the latest `asf-site`.

**Comment by MartijnVisser** [comment]
Resolved by the migration to Hugo via https://issues.apache.org/jira/browse/FLINK-22922

**Pull request closed without merging**
