### PR TITLE
[FLINK-11527] Support multiple languages for the framework of flink-web

### PR DESCRIPTION
**Pull request by wuchong**
## What is the purpose of the change

This changes update the framework to support English and Chinese at the same time.

I excluded the `/content` file changes to make the PR easy to review.

## Brief change log
* integrate the `jekyll-multiple-languages` plugin.
* upgrade jekyll to '3.0.5' in Gemfile, because `jekyll-multiple-languages` depends on it.
* add `_data/i18n.yml` and update `_include/navbar.html` to support Chinese & English for sidebar.
* copy all the `xxx.md` to `xxx.zh.md` but keep the original English contents.
* I didn't copy the `xxx.zh.md` for the `/blog` and `/_post` files. I'm not sure whether we need to translate them, so the link of "Flink Blog" in Chinese website still link to "http://0.0.0.0:4000/blog/"

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for the PR @wuchong.
I'll have a look soon.

Cheers, Fabian

**Comment by fhueske** [comment]
Hi @wuchong, the PR looks good.
One thought, do you think it would be helpful if the language switch would link to the same page (of the other language) instead of the start page. For example, if you are on the English community page, the language link would lead to the Chinese community page. 

It might not be super important for the website (because it is fairly small) but for the docs with many pages it might be helpful.

Thanks, Fabian

**Comment by wuchong** [comment]
@fhueske , I think it's a good idea. I have updated the PR. Note that we don't translate the blog pages, so when you are on the English blog page, the language link would link to the Chinese home page.

**Comment by fhueske** [comment]
Hi Jark, thanks for the update.
I noticed that on the Chinese pages page-internal links stay in the same language, while links to another page always point to the English version. I guess that's just how it is until the Chinese page gets translated and the links are adjusted.

+1 to merge the PR. 
Do you want to merge it or should I do it?

**Comment by wuchong** [comment]
Hi @fhueske , you are right. The links will be adjusted when translating.

I will try to merge this.  :)

**Comment by fhueske** [comment]
Thank you!

**Pull request closed without merging**
