### PR TITLE
[hotfix][docs] Delete the redundant content of "downloads.zh.md" file.

### PR DESCRIPTION
**Pull request by liuzhuang2017**
# English document
image
# Chinese document 
image

- **From the above picture of Chinese and English documents, it can be seen that there is a part of English content in Chinese documents.**

### CODE REVIEW

**Comment by liuzhuang2017** [comment]
@MartijnVisser ,Sorry to bother you, can you help me review this pr? Thank you.

**Comment by liuzhuang2017** [comment]
@MartijnVisser ,Sorry to bother you again, can you help me review this pr? Thank you.

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Comment by liuzhuang2017** [comment]
@MartijnVisser , Thank you very much for your review.

**Pull request merged**
