### PR TITLE
Update index.html and index.md

### PR DESCRIPTION
**Pull request by sahitya-pavurala**
Fixed the link to programming guide link on the content/index.html

### CODE REVIEW

**Comment by rmetzger** [comment]
Thank you for this pull request.
The files in `content/` are actually generated from the files in the root directory.
So your change will be overwritten by anyone who is going to update the files in the root directory.

Can you make the change in the `./index.html` as well?

**Comment by sahitya-pavurala** [comment]
I didnt really find the other index.html which you meant, can you be please more specific? Thanks

**Comment by sahitya-pavurala** [comment]
I see what you meant , the index.md is the one generating the file, so I need to change that.

**Comment by sahitya-pavurala** [comment]
I made the change, please check.

**Comment by rmetzger** [comment]
Looks great now .. I'm going to merge it.

**Pull request closed without merging**
