### PR TITLE
Add Pulsar connector v4.1.0 release

### PR DESCRIPTION
**Pull request by leonardBang**
Add Pulsar connector v4.1.0 release

### CODE REVIEW

**Review by 1996fanrui — APPROVED** [review]
Thanks @leonardBang for this PR!

LGTM.

**Review by tisonkun — APPROVED** [review]
Thank you!

**Review by ruanhang1993 — APPROVED** [review]
LGTM.

**Review by dannycranmer — APPROVED** [review]
LGTM, thanks @leonardBang

**Review by snuyanzin — APPROVED** [review]

**Review by PatrickRen — APPROVED** [review]
LGTM

**Pull request closed without merging**
