### PR TITLE
[FLINK-34968] Update flink-web copyright to 2024

### PR DESCRIPTION
**Pull request by yuchen-ecnu**

### CODE REVIEW

**Review by Myasuka — COMMENTED** [review]
Thanks for creating this PR, please rebuild the website to resolve the conflicts.

**Comment by yuchen-ecnu** [comment]
> Thanks for creating this PR, please rebuild the website to resolve the conflicts.

Hi @Myasuka , thanks for the review. I have rebuilt the website, and there are no conflicts for now.

**Review by reswqa — APPROVED** [review]
Thanks for the update.

**Review by Myasuka — APPROVED** [review]
LGTM.

**Pull request merged**
