### PR TITLE
Add xtsong to the committer list.

### PR DESCRIPTION
**Pull request by xintongsong**

### CODE REVIEW

**Comment by zhuzhurk** [comment]
The rebuilt web should be in a separate commit I think.

**Comment by morsapaes** [comment]
Hey, @xintongsong (Tony!).

This should only contain the markdown files you're touching and not any translated files, as outlined in the [contribution guidelines](https://flink.apache.org/contributing/improve-website.html#submit-your-contribution). Whoever takes care of the PR should then rebuild the website when merging!

**Comment by xintongsong** [comment]
Thanks for the reminder @zhuzhurk, and thanks for the pointer @morsapaes (Marta!)
PR updated.

**Comment by zhuzhurk** [comment]
Hi @xintongsong , another commit is needed which contains the rebuilt web files.

**Comment by zhuzhurk** [comment]
Just ignore my last comment.
I checked the contribution doc again and find I was wrong. 
The commit for rebuilt web files are not needed in the PR.
The committer should do it when merging the pull request.

**Review by zhuzhurk — APPROVED** [review]
The change looks good to me.

**Comment by xintongsong** [comment]
Thanks @zhuzhurk, merging this.

**Pull request closed without merging**
