### PR TITLE
Add KUDO Flink fraud detection post

### PR DESCRIPTION
**Pull request by gerred**
This PR adds a KUDO post for the Flink fraud detection demo.

### CODE REVIEW

**Comment by gerred** [comment]
Hey @tillrohrmann  - are you sure? I can't reproduce when running it with Docker, and I see the pngs in the files changed. What are you seeing? Is there another path I should place them under?

**Comment by fhueske** [comment]
Hi, the new images in the `./img/` folder have 0 bytes. 
When building the website to preview, these images override the images in `./content/img`.

I'll have a closer look at the post tomorrow. 

Best, Fabian

**Comment by gerred** [comment]
@fhueske yep, that makes sense, I messed that up and fixed it in `./content/img`. I'll fix that up real quick.

**Comment by gerred** [comment]
fixed!

**Comment by fhueske** [comment]
Hi @gerred, thanks for the nice post!
I tried to follow the steps but had some difficulties because I'm on Linux and not on a Mac. Specifically, I ran into the following problems:

* The installation guide for non-brew users is not very clear. Can you describe the necessary steps or link to the right page in the documentation that describes how to install KUDO?
* the command `minikube start --vm-driver=hyperkit --cpus=6 --memory=9216 --disk-size=10g` told me that the `hyperkit` driver is not available on Linux
* the command `kubectl kudo install zookeeper --version=0.1.0 --skip-instance` returned the following error:

> Error: failed to resolve package CRDs for operator: zookeeper: while extracting package files: failed to unmarshal operator file: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field Operator.tasks of type []v1beta1.Task

Could it be caused by a incorrect Go installation? (If Go is required, it would be good to mention this in the post).

It would also be nice to add an `excerpt` like [this post](https://raw.githubusercontent.com/apache/flink-web/asf-site/_posts/2019-03-06-ffsf-preview.md) did to shorten the preview on the `index.html` page.

Could you also remove the changes in `./content` from the PR? It makes the PR smaller and we are updating the content before merging and publishing the new website.

Thank you,
Fabian

**Comment by gerred** [comment]
Thanks @fhueske! I'll get those fixed. Fortunately, Go is not required, but there might be some versioning issue there. I'll take a look.

**Comment by gerred** [comment]
@fhueske I've made these updates - I'm on low bandwidth so it'll take me a day or so to test them out (pulling Docker images over low bandwidth is always fun), but I updated some versions to reflect the latest version of KUDO and it's operators.

**Comment by gerred** [comment]
Ready for review!

**Comment by fhueske** [comment]
Hi @gerred, sorry for the slow response! 
I'm traveling right now.
Hope to have a look at it in the next days.

Fabian

**Comment by gerred** [comment]
Hey, no problem @fhueske, thanks for the update. Safe travels. :)

**Comment by gerred** [comment]
@rmetzger :+1: Ready to go! No concerns on timing on my end.

**Comment by rmetzger** [comment]
Thanks. I published the blog post!

**Comment by mabuchwald** [comment]
Thanks everyone! Great work!

**Pull request closed without merging**
