### PR TITLE
Create Japanese Edition.

### PR DESCRIPTION
**Pull request by t-eimizu**
A Japanese version of this page has been created. There are still a few more pages in English, but I will continue to translate them into Japanese.

### CODE REVIEW

**Comment by rmetzger** [comment]
Thanks a lot for your contribution!
Adding another language for the Flink website is a pretty big change. Before we do that, I would like to discuss this with the community (on the dev@ mailing list). I'm starting a thread there ...

**Comment by rmetzger** [comment]
Here's the thread: https://lists.apache.org/thread.html/rb014261aed061a9c225181a163dce60a49a5f65694c9fbfe4e1f42e4%40%3Cdev.flink.apache.org%3E

**Comment by rmetzger** [comment]
Thanks again for your pull request. I am personally quite excited about the idea of adding Japanese to the list of languages that Flink offers :)

As you can see from the linked email thread, the community currently has nobody who speaks Japanese to review the pull request.
Secondly, we are unhappy with our current tooling to maintain a bilingual website / documentation. It is a lot of work to keep our Chinese documentation in sync with the English reference.

Given this discussion outcome, we have to ask you to wait potentially a few month until we have figured out the tooling situation. In the meantime, I will try to see if find somebody in the community who speaks Japanese.

**Comment by MartijnVisser** [comment]
Closing this PR due to inactivity / other priorities

**Pull request closed without merging**
