### PR TITLE
Add Kuaishou to PowerBy page

### PR DESCRIPTION
**Pull request by wuchong**
The preview:

http://0.0.0.0:4000/poweredby.html
image

http://0.0.0.0:4000/zh/poweredby.html
image

### CODE REVIEW

**Comment by wuchong** [comment]
Hi @rmetzger @fhueske , do you need to have a look?

**Comment by rmetzger** [comment]
Thanks for opening this pull request. Do we have approval by Kuaishou to put their logo and this text on the Flink website?

**Comment by wuchong** [comment]
Hi @rmetzger , yes. I have contacted with Kuaishou employees with email and get the permission. I didn't post the email yet. 
And the same with the other PR for Didi.

**Comment by rmetzger** [comment]
Great! Thanks for confirming.
@fhueske good to go?

**Comment by fhueske** [comment]
Thanks for the PR @wuchong!

Merging :-)

**Pull request closed without merging**
