### PR TITLE
Fix typo in contribute-code: "sensitive" vs "sensible"

### PR DESCRIPTION
**Pull request by apjanke**
Doco has "sensible" where it should be "sensitive".

Fixes https://issues.apache.org/jira/browse/FLINK-9447

### CODE REVIEW

**Comment by fhueske** [comment]
Thanks for the fix!
+1 to merge

**Comment by fhueske** [comment]
Merged

**Comment by fhueske** [comment]
Hi @apjanke, the PR has been merged.
Could you please close the PR?

Thank you, Fabian

**Comment by apjanke** [comment]
Closed. Thanks!

**Pull request closed without merging**
